/* -------------------------------------------------------------------------- */
/* Make PUNKTINFOTYPE data. 
/* File: MakePunktInfoType.sql   
/* -------------------------------------------------------------------------- */

/*
AFKLARINGER:
Er namespace listen komplet - modellens enum passer ikke med Kristians regneark
Mangler at implementere AFM:højde_over_ATTRIBUT

*/
DELETE FROM PUNKTINFOTYPENAMESPACE;
INSERT INTO PUNKTINFOTYPENAMESPACE (BESKRIVELSE, NAMESPACE) VALUES ('Ingen beskrivelse','AFM');
INSERT INTO PUNKTINFOTYPENAMESPACE (BESKRIVELSE, NAMESPACE) VALUES ('Ingen beskrivelse','ATTR');
INSERT INTO PUNKTINFOTYPENAMESPACE (BESKRIVELSE, NAMESPACE) VALUES ('Ingen beskrivelse','IDENT');
INSERT INTO PUNKTINFOTYPENAMESPACE (BESKRIVELSE, NAMESPACE) VALUES ('Ingen beskrivelse','NET');
INSERT INTO PUNKTINFOTYPENAMESPACE (BESKRIVELSE, NAMESPACE) VALUES ('Ingen beskrivelse','PS');
INSERT INTO PUNKTINFOTYPENAMESPACE (BESKRIVELSE, NAMESPACE) VALUES ('Ingen beskrivelse','REGION');
INSERT INTO PUNKTINFOTYPENAMESPACE (BESKRIVELSE, NAMESPACE) VALUES ('Ingen beskrivelse','SKITSE');

DELETE FROM PUNKTINFOTYPE;

-- AFM
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('TEKST','Diverse ikke-standardiserede afmærkningstyper','AFM:diverse');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','Horisontalt fikspunkt','AFM:horisontal');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','Vertikalt fikspunkt','AFM:vertikal');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','Horisontalt+vertikalt fikspunkt','AFM:horisontalvertikal');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','Naturligt fikspunkt','AFM:naturlig');
-- AFM:xxx (311 stk)
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE)
SELECT 'TEKST', s.TEKST, 'AFM:' || s.AFMTYP
FROM (
    SELECT DISTINCT AFMTYP, TEKST FROM AFMTYP_TXT@refgeo WHERE TEKST != 'p_afmtxt' ORDER BY AFMTYP, TEKST
) s;

-- AFM:højde_over_xxx (12 stk)
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE)
SELECT 'TAL', 'Afmærkningens højde i meter over ' || s.INFOTYPE, 'AFM:højde_over_' || s.INFOTYPE
FROM (
    SELECT DISTINCT trim('.' FROM tekst) AS INFOTYPE FROM height_txt@refgeo WHERE tekst IS NOT NULL OR trim(tekst) != ''
) s;

-- ATTR
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','Tilgang kun tilladt internt i SDFE','ATTR:restricted');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','Fysisk punkt ikke længere tilgængeligt','ATTR:tabtgået');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','Ikke etableret af SDFE','ATTR:ekstern');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','Punktet er en vandstandsmåler','ATTR:vandstandsmåler');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','Punktet er egnet til GNSS opmåling','ATTR:gnss_egnet');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('TEKST','Beskrivelse af punktets placering','ATTR:beskrivelse');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','Højdefikspunkter','ATTR:højdefikspunkt');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','MV fikspunkter','ATTR:MV_punkt');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','GI fikspunkter','ATTR:GI_punkt');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','Hjælpepunkter','ATTR:hjælpepunkt');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('TEKST','Sagsnummer i tinglysningsbogen','ATTR:tinglysningsnr');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('TEKST','Bemærkning til punkt','ATTR:bemærkning');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('FLAG','Kote-afmærkningen tabtgået, skæv eller beskadiget','ATTR:beskadiget');

-- IDENT
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('TEKST','Landsnummer','IDENT:landsnr');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('TEKST','GNNS Stationsnummer','IDENT:GNSS');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('TEKST','ID (refnr) fra REFGEO','IDENT:refgeo_id');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('TEKST','Jessennummer','IDENT:jessen');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('TEKST','GI og GM-nummre','IDENT:GI');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE) VALUES ('TEKST','Identtyper der forekommer sporadisk','IDENT:diverse');

-- NET
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','Punkter der indgår i 10kmnet','NET:10KM');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','Punkter der indgår i GPSnet','NET:GPSNET');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','Punkter der indgår i Refdknet','NET:REFDK');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','Punkter der indgår i 5D-nettet','NET:5D');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','DMIs vandstandsmålere','NET:DMI');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','Punkter hvor der foretages tyngdemåling','NET:tyngde');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','Jessenpunkter','NET:jessen');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','Punkter i det færøske 10km net','NET:FO10KM');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','Contiously Operating Reference Stations - Permanente GNSS stationer','NET:CORS');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','Definerende punkter i ETRS89','NET:EUREFDK');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','Definerende vandstandsmålere i DVR90','NET:DEFVAND');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','Referencenetpunkter i Grønland','NET:REFGR');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('FLAG','Afmærkninger ved den Dansk-Tyske grænse','NET:GRAENSEAFM');

-- REGION
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE, INFOTYPE)
SELECT 'FLAG', s.TEKST, 'REGION:' || s.INFOTYPE
FROM (
    SELECT DISTINCT rg.RGN_PRFX AS INFOTYPE, rg.RGN_NAME AS TEKST 
    FROM HVD_REF@refgeo href 
    INNER JOIN RGN_TABLE@refgeo rg ON href.RGN = rg.RGN_NO
) s;

-- SKITSE
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('TEKST','Relativ sti til billedfil. Kan enten være i PNG eller SVG format','SKITSE:sti');
INSERT INTO PUNKTINFOTYPE (ANVENDELSE, BESKRIVELSE,INFOTYPE) VALUES ('TEKST','MD5 sum af billedfilen','SKITSE:md5');


COMMIT;

