/* -------------------------------------------------------------------------- */
/* Make PUNKTINFO data (with namespace IDENT).
/* Data is mainly found in the dedicated lookup table generated by Kristian and
/* based on the output of a script. The REFNR ident is fetched from the table CONV_PUNKT 
/* File: MakePunktInfoAFM.sql   
/* -------------------------------------------------------------------------- */

DELETE FROM PUNKTINFO WHERE INFOTYPE LIKE 'IDENT:%';

-- IDENT:refgeo_id
INSERT INTO PUNKTINFO (REGISTRERINGFRA, REGISTRERINGTIL, INFOTYPE, TEKST, SAGSEVENTID, PUNKTID)
SELECT 
    p.REGISTRERINGFRA AS REGISTRERINGFRA,
    p.REGISTRERINGTIL AS REGISTRERINGTIL,
    'IDENT:refgeo_id' AS INFOTYPE,
    conv.REFNR AS TEKST,
    '15101d43-ac91-4c7c-9e58-c7a0b5367910' AS SAGSEVENTID,
    conv.ID AS PUNKTID
FROM PUNKT p
INNER JOIN CONV_PUNKT conv ON p.ID = conv.ID
;

-- IDENT:landsnr
-- IDENT:GNSS
-- IDENT:jessen (tastefejl, ressen->jessen)
-- IDENT:GI
-- IDENT:diverse
INSERT INTO PUNKTINFO (REGISTRERINGFRA, REGISTRERINGTIL, INFOTYPE, TEKST, SAGSEVENTID, PUNKTID)
SELECT 
    p.REGISTRERINGFRA AS REGISTRERINGFRA,
    p.REGISTRERINGTIL AS REGISTRERINGTIL,
    'IDENT:' || CASE WHEN ident.IDENT_TYPE = 'ressen' THEN 'jessen' ELSE ident.IDENT_TYPE END AS INFOTYPE,
    ident.IDENT AS TEKST,
    '15101d43-ac91-4c7c-9e58-c7a0b5367910' AS SAGSEVENTID,
    conv.ID AS PUNKTID
FROM PUNKT p
INNER JOIN CONV_PUNKT conv ON p.ID = conv.ID
INNER JOIN refadm.REFNR_IDENT@refgeo ident ON ident.REFNR = conv.REFNR
;


COMMIT;