/* -------------------------------------------------------------------------- */
/* Make PUNKTINFO data (with namespace REGION).
/* Data is found in REFGEO tables HVD_REF and RGN_TABLE 
/* File: MakePunktInfoREGION.sql   
/* -------------------------------------------------------------------------- */
/*
SPØRGSMÅL
*/

DELETE FROM PUNKTINFO WHERE INFOTYPEID IN (SELECT INFOTYPEID FROM PUNKTINFOTYPE WHERE INFOTYPE LIKE 'REGION:%');

-- REGION:xxx
INSERT INTO PUNKTINFO (REGISTRERINGFRA, REGISTRERINGTIL, INFOTYPEID, SAGSEVENTFRAID, PUNKTID)
SELECT 
    p.REGISTRERINGFRA AS REGISTRERINGFRA,
    NULL AS REGISTRERINGTIL,
    (SELECT INFOTYPEID FROM PUNKTINFOTYPE WHERE INFOTYPE = 'REGION:' || r.RGN_PRFX AND ROWNUM <= 1) AS INFOTYPEID,
    '15101d43-ac91-4c7c-9e58-c7a0b5367910' AS SAGSEVENTFRAID,
    conv.ID AS PUNKTID
FROM PUNKT p
INNER JOIN CONV_PUNKT conv ON p.ID = conv.ID
INNER JOIN HVD_REF@refgeo href ON href.REFNR = conv.REFNR
INNER JOIN RGN_TABLE@refgeo r ON href.RGN = r.RGN_NO
;

COMMIT;