/* -------------------------------------------------------------------------- */
/* Sample SQL to get information about a punkt, observation and beregning. 
/* SQL assumes that you are using the REFNR as identifier when obtaining info
/* about punkt (including geometri, punktinfo and koordinat)
/* For observation the SQL assumes you are using the REFNR of the opstillingspunkt
/* For beregning the SQL assumes you are using the beregning sagseventid.   
/* -------------------------------------------------------------------------- */

-- Find FIRE ID for et punkt med kendt REFNR
SELECT * FROM CONV_PUNKT WHERE REFNR = 633;

-- Punkt
SELECT * FROM PUNKT WHERE ID = (SELECT ID FROM CONV_PUNKT WHERE REFNR = 633) ORDER BY REGISTRERINGFRA;

-- Geometriobjekt
SELECT * FROM GEOMETRIOBJEKT WHERE PUNKTID = (SELECT ID FROM CONV_PUNKT WHERE REFNR = 633) ORDER BY REGISTRERINGFRA;

-- Punktinfo
SELECT p.*, t.INFOTYPE FROM PUNKTINFO p INNER JOIN PUNKTINFOTYPE t ON p.INFOTYPEID = t.INFOTYPEID WHERE PUNKTID = (SELECT ID FROM CONV_PUNKT WHERE REFNR = 633) ORDER BY t.INFOTYPE, p.REGISTRERINGFRA;

-- Koordinat
SELECT k.*, t.SRID FROM KOORDINAT k INNER JOIN SRIDTYPE t ON k.SRIDID = t.SRIDID WHERE k.PUNKTID = (SELECT ID FROM CONV_PUNKT WHERE REFNR = 633) ORDER BY t.SRID, k.REGISTRERINGFRA;

-- Observation
SELECT o.*, t.OBSERVATIONSTYPE FROM OBSERVATION o INNER JOIN OBSERVATIONTYPE t ON o.OBSERVATIONSTYPEID = t.OBSERVATIONSTYPEID WHERE o.OPSTILLINGSPUNKTID = (SELECT ID FROM CONV_PUNKT WHERE REFNR = 633) ORDER BY t.OBSERVATIONSTYPE, o.REGISTRERINGFRA;

-- Koordinater i beregning
SELECT * 
FROM BEREGNING b
INNER JOIN BEREGNING_KOORDINAT bk ON b.OBJECTID = bk.BEREGNINGOBJECTID
INNER JOIN KOORDINAT k ON k.OBJECTID = bk.KOORDINATOBJECTID 
WHERE b.SAGSEVENTID = '7C581B4A-6299-7F16-E053-1A041EAC3A76'
;
-- Punkter i beregning
SELECT * 
FROM BEREGNING b
INNER JOIN BEREGNING_OBSERVATION bo ON b.OBJECTID = bo.BEREGNINGOBJECTID
INNER JOIN OBSERVATION o ON o.OBJECTID = bo.OBSERVATIONOBJECTID 
WHERE b.SAGSEVENTID = '7C581B4A-6299-7F16-E053-1A041EAC3A76'
;

