SELECT 
    'PUNKT' AS TABLENAME, NULL AS INFOTYPE, 
    SUM(CASE WHEN REGISTRERINGTIL IS NULL THEN 1 ELSE 0 END) AS CURRENTINSTANSES, 
    SUM(CASE WHEN REGISTRERINGTIL IS NOT NULL THEN 1 ELSE 0 END) AS PREVIOUSINSTANSES, 
    COUNT(REGISTRERINGFRA) AS TOTALINSTANSES
FROM PUNKT
GROUP BY 1
UNION ALL 
SELECT 
    'GEOMETRIOBJEKT' AS TABLENAME, NULL AS INFOTYPE, 
    SUM(CASE WHEN REGISTRERINGTIL IS NULL THEN 1 ELSE 0 END) AS CURRENTINSTANSES, 
    SUM(CASE WHEN REGISTRERINGTIL IS NOT NULL THEN 1 ELSE 0 END) AS PREVIOUSINSTANSES, 
    COUNT(REGISTRERINGFRA) AS TOTALINSTANSES
FROM GEOMETRIOBJEKT 
GROUP BY 1
UNION ALL 
SELECT 
    'KOORDINAT' AS TABLENAME, SRID AS INFOTYPE, 
    SUM(CASE WHEN REGISTRERINGTIL IS NULL THEN 1 ELSE 0 END) AS CURRENTINSTANSES, 
    SUM(CASE WHEN REGISTRERINGTIL IS NOT NULL THEN 1 ELSE 0 END) AS PREVIOUSINSTANSES, 
    COUNT(REGISTRERINGFRA) AS TOTALINSTANSES
FROM KOORDINAT 
GROUP BY SRID
UNION ALL 
SELECT 
    'PUNKTINFO' AS TABLENAME, INFOTYPE AS INFOTYPE, 
    SUM(CASE WHEN REGISTRERINGTIL IS NULL THEN 1 ELSE 0 END) AS CURRENTINSTANSES, 
    SUM(CASE WHEN REGISTRERINGTIL IS NOT NULL THEN 1 ELSE 0 END) AS PREVIOUSINSTANSES, 
    COUNT(REGISTRERINGFRA) AS TOTALINSTANSES
FROM PUNKTINFO 
GROUP BY INFOTYPE
UNION ALL 
SELECT 
    'OBSERVATION' AS TABLENAME, OBSERVATIONSTYPE AS INFOTYPE, 
    SUM(CASE WHEN REGISTRERINGTIL IS NULL THEN 1 ELSE 0 END) AS CURRENTINSTANSES, 
    SUM(CASE WHEN REGISTRERINGTIL IS NOT NULL THEN 1 ELSE 0 END) AS PREVIOUSINSTANSES, 
    COUNT(REGISTRERINGFRA) AS TOTALINSTANSES
FROM OBSERVATION 
GROUP BY OBSERVATIONSTYPE
ORDER BY TABLENAME, INFOTYPE
;
